version: '3.8'

services:
  todoapp:
    image: todoapp  # Replace with your actual Docker image for todoapp
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgresdb  # Ensure PostgreSQL container is started first

  postgresdb:
    image: postgres:10
    environment:
      POSTGRES_DB: todoappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL default port
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data

volumes:
  postgres-data:
